import pyttsx3
import datetime
import time
import random
from playsound import playsound

engine = pyttsx3.init('sapi5')
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[0].id)
rate = engine.getProperty('rate')
engine.setProperty('rate', 150)

def speak(audio):
    engine.say(audio)
    engine.runAndWait()

onetime = "Hi. I'm Iris. Your health monitoring artificial assistant. My job is to make sure you're healthy and fit on a physical, mental and emotional level while you hustle 24 7."
print(onetime)
speak(onetime)

def healthy():
    print("Let's start with the eye healthcare.")
    speak("Let's start with the eye healthcare.")
    time.sleep(2)
    speak("Please be seated properly.")
    print("Zooming")
    speak("Zooming")
    time.sleep(2)
    print("Take your index finger and focus on it and gradually move it back and forth. Take the position. Right hand first.")
    speak("Take your index finger and focus on it and gradually move it back and forth. Take the position. Right hand first.")
    time.sleep(4)
    speak("Point the finger at about 3 inches.")
    time.sleep(2)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Now with the left hand.")
    time.sleep(2)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    speak("Move away")
    time.sleep(4)
    speak("Bring close")
    time.sleep(4)
    print("Shifting")
    speak("Shifting")
    time.sleep(2)
    print("Take your thumb and stretch your arm at maximum distance. Look for an object about 20 feet away to focus on. Take the position. Right hand first.")
    speak("Take your thumb and stretch your arm at maximum distance. Look for an object about 20 feet away to focus on. Take the position. Right hand first.")
    time.sleep(2)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Now with the left hand.")
    time.sleep(2)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    speak("Focus on Thumb")
    time.sleep(4)
    speak("Focus on Object")
    time.sleep(4)
    print("Figure 8")
    speak("Figure 8")
    time.sleep(2)
    print("Look for a point on the floor 10 feet away and imagine figure 8 shape. Move your eyes along the shape. Take the position. Clockwise first.")
    speak("Look for a point on the floor 10 feet away and imagine figure 8 shape. Move your eyes along the shape. Take the position. Clockwise first.")
    time.sleep(2)
    speak("Start")
    time.sleep(16)
    speak("Now counter clockwise.")
    time.sleep(2)
    speak("Start")
    time.sleep(16)
    print("Now Figure 8 thumb. Stretch your arm at maximum distance and focus on the thumb. Start rotating in figure 8 shape. Follow along with eyes. Take the position. Right thumb first. Clockwise first.")
    speak("Now Figure 8 thumb. Stretch your arm at maximum distance and focus on the thumb. Start rotating in figure 8 shape. Follow along with eyes. Take the position. Right thumb first. Clockwise first.")
    time.sleep(2)
    speak("Start")
    time.sleep(16)
    speak("Now counter clockwise.")
    time.sleep(16)
    speak("Now with the left hand. Clockwise.")
    time.sleep(2)
    speak("Start")
    time.sleep(16)
    speak("Now counter clockwise.")
    time.sleep(16)
    print("Palming")
    speak("Palming")
    time.sleep(2)
    print("Rub your hands rigorously till warm. Put open plams on closed eye lids. Don't press too hard. Take the position.")
    speak("Rub your hands rigorously till warm. Put open plams on closed eye lids. Don't press too hard. Take the position.")
    time.sleep(2)
    speak("Rub")
    time.sleep(10)
    speak("Apply")
    time.sleep(5)
    speak("Rub")
    time.sleep(10)
    speak("Apply")
    time.sleep(5)
    speak("Rub")
    time.sleep(10)
    speak("Apply")
    time.sleep(5)
    print("Blinking")
    speak("Blinking")
    time.sleep(2)
    print("Blink with increasing intensity for the next  15 blinks. Close your eyes after. Take the position.")
    speak("Blink with increasing intensity for the next  15 blinks. Close your eyes after. Take the position.")
    time.sleep(2)
    speak("Start Blinking")
    time.sleep(8)
    speak("Close your eyes")
    time.sleep(20)
    speak("Start Blinking")
    time.sleep(8)
    speak("Close your eyes")
    time.sleep(20)
    print("Directions")
    speak("Directions")
    time.sleep(2)
    print("CLose your eyes and move them in the directed direction. Take the position.")
    speak("CLose your eyes and move them in the directed direction. Take the position.")
    time.sleep(2)
    speak("Left")
    time.sleep(4)
    speak("Right")
    time.sleep(4)
    speak("Up")
    time.sleep(4)
    speak("Down")
    time.sleep(4)
    speak("Roll Clockwise")
    time.sleep(4)
    speak("Roll Counter clockwise")
    time.sleep(4)
    print("Great. You're done with the eye healthcare. Remember to wash your eyes with cold water.")
    speak("Great. You're done with the eye healthcare. Remember to wash your eyes with cold water.")
    time.sleep(2)
    speak("Please ensure you look away from the computer screen every 20 minutes at a 20 feet distant object for 20 seconds.")
    time.sleep(2)
    speak("Also walk a bit, breathe and drink water. Get enough sleep and food. Avoid social media or phone usage.")
    speak("Don't have emotional disappointment. Have a great time working boss.")

def timefunction():
    hrsn = int(datetime.datetime.now().hour)
    minsn = int(datetime.datetime.now().minute)
    secsn = int(datetime.datetime.now().second)
    if hrsn == 0 and minsn == 0:
        healthy()
    elif hrsn == 1 and minsn == 0:
        healthy()
    elif hrsn == 2 and minsn == 0:
        healthy()
    elif hrsn == 3 and minsn == 0:
        healthy()
    elif hrsn == 4 and minsn == 0:
        healthy()
    elif hrsn == 5 and minsn == 0:
        healthy()
    elif hrsn == 6 and minsn == 0:
        healthy()
    elif hrsn == 7 and minsn == 0:
        healthy()
    elif hrsn == 8 and minsn == 0:
        healthy()
    elif hrsn == 9 and minsn == 0:
        healthy()
    elif hrsn == 10 and minsn == 0:
        healthy()
    elif hrsn == 11 and minsn == 0:
        healthy()
    elif hrsn == 12 and minsn == 0:
        healthy()
    elif hrsn == 13 and minsn == 0:
        healthy()
    elif hrsn == 14 and minsn == 0:
        healthy()
    elif hrsn == 15 and minsn == 0:
        healthy()
    elif hrsn == 16 and minsn == 0:
        healthy()
    elif hrsn == 17 and minsn == 0:
        healthy()
    elif hrsn == 18 and minsn == 0:
        healthy()
    elif hrsn == 19 and minsn == 0:
        healthy()
    elif hrsn == 20 and minsn == 0:
        healthy()
    elif hrsn == 21 and minsn == 0:
        healthy()
    elif hrsn == 22 and minsn == 0:
        healthy()
    elif hrsn == 23 and minsn == 0:
        healthy()

x = 1
while x == 1:
    timefunction()
