# -*- coding: utf-8 -*-
"""Conf_Scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RI_PvSSKJl-t3dGJNxeTIXiRXPbrbzyM
"""

!pip install git+https://github.com/alirezamika/autoscraper.git



from autoscraper import AutoScraper

url = 'http://wikicfp.com/cfp/call?conference=medical%20imaging&page=2'
category = ['Event']

scrape = AutoScraper()
final = scrape.build(url, category)
print(final[])

for i in range(6,len(final),5):
  print(final[i]+'\n')

"""# **Main Code Begins Here --**"""

import pandas as pd
import numpy as np

single_topics = ['5G','aerospace','automation','blockchain','bussiness','cancer','economics']
double_topics = [['medical','imaging'],['fuzzy','systems']]

events = []
category=['Event']

#Scraping the first 5 pages
pages = np.arange(1,5,1)

for i in range(len(single_topics)):
  
  #Scraping the first 5 pages 
  for page in pages:
      url = 'http://wikicfp.com/cfp/call?conference='+str(single_topics[i])+'&page='+str(page)
      scrape = AutoScraper()
      final = scrape.build(url, category)

      for j in range(6,len(final),5):
        events.append(final[j])
      
  df = pd.DataFrame({
      'Name of Event' : events
        })
  df.to_csv(str(single_topics[i])+'_events.csv')

